name: Release to DockerHub
on:
  push:
    tags:
      - 'v*'  # Launch DockerHub push on v* tags (e.g.: v1.2.1)
env:
  IMAGE_REGISTRY: "ghcr.io"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log into registry ${{ env.IMAGE_REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish
        uses: 0x4r45h/docker-compose-ci@2d9ea175600441004c7821462293a31c47c38fc4 # v0.1.1
        with:
          docker_compose_files: '-f docker/docker-compose.yml'
          services: "release"
